# Generated by Django 3.1.3 on 2020-11-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('deadline', models.DateTimeField(verbose_name='deadline')),
            ],
        ),
    ]
