# Generated by Django 3.1.3 on 2020-11-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='periode',
            field=models.CharField(default='day', max_length=10),
        ),
    ]
