# Generated by Django 3.1.3 on 2020-11-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_periode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='periode',
        ),
        migrations.AddField(
            model_name='todo',
            name='recurring',
            field=models.CharField(default='d', max_length=10),
        ),
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateTimeField(),
        ),
    ]
